FROM ruby:3.3.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

RUN mkdir /rails

WORKDIR /rails

COPY Gemfile /rails/Gemfile
COPY Gemfile.lock /rails/Gemfile.lock

RUN bundle install

COPY . /rails

CMD bundle exec sidekiq
